AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  AlimentAPP - Backend base (solo seguridad). Crea el Security Group para Lambdas
  y autoriza acceso a RDS en 5432 desde dicho SG.

Parameters:
  VpcId:
    Type: String
    Description: VPC ID donde viven las Lambdas y RDS
  RdsSecurityGroupId:
    Type: String
    Description: Security Group ID del RDS (Output del stack de red)
  DbPort:
    Type: Number
    Default: 5432
    Description: Puerto de PostgreSQL

Resources:
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for Lambdas (access to RDS only)
      VpcId: !Ref VpcId
      # Egress por defecto (allow all). El acceso real queda restringido por el ingress del RDS.
      Tags:
        - Key: Name
          Value: alimentapp-lambda-sg

  DbIngressFromLambda:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref RdsSecurityGroupId
      IpProtocol: tcp
      FromPort: !Ref DbPort
      ToPort: !Ref DbPort
      SourceSecurityGroupId: !Ref LambdaSecurityGroup
      Description: Allow Postgres from Lambda SG

Outputs:
  LambdaSecurityGroupId:
    Value: !Ref LambdaSecurityGroup
    Description: Security Group para asociar a las funciones Lambda
