AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  AlimentAPP - VPC privada sin NAT y RDS PostgreSQL (Free Tier). Crea VPC con
  subredes privadas aisladas y una instancia RDS Postgres privada.

Parameters:
  VpcCidr:
    Type: String
    Default: 10.20.0.0/16
    Description: CIDR de la VPC
  DBName:
    Type: String
    Default: frozen
  DBUser:
    Type: String
    Default: admin
    MinLength: 1
  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Password del usuario maestro (no se mostrará en outputs)
  DBInstanceClass:
    Type: String
    Default: db.t4g.micro
    AllowedValues:
      - db.t4g.micro
      - db.t3.micro
    Description: Clases elegibles en Free Tier (12 meses)
  DBAllocatedStorage:
    Type: Number
    Default: 20
    MinValue: 20
    Description: GiB de almacenamiento (Free Tier hasta 20 GB)
  BackupRetentionDays:
    Type: Number
    Default: 3
    MinValue: 0
    MaxValue: 7
    Description: Mantener bajo para no exceder los 20 GB de backups del Free Tier
  DeletionProtection:
    Type: String
    AllowedValues: [true, false]
    Default: false
  EngineVersion:
    Type: String
    Default: '15'
    Description: Versión mayor de Postgres (RDS elegirá un minor soportado)

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: alimentapp-vpc

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: 10.20.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: alimentapp-private-a

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: 10.20.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: alimentapp-private-b

  PrivateRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: alimentapp-rtb-private-a

  PrivateRouteTableB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: alimentapp-rtb-private-b

  PrivateSubnetRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetA
      RouteTableId: !Ref PrivateRouteTableA

  PrivateSubnetRouteTableAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetB
      RouteTableId: !Ref PrivateRouteTableB

  RdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acceso a RDS solo desde SG de Lambdas (se agrega en backend)
      VpcId: !Ref Vpc
      SecurityGroupEgress: []
      SecurityGroupIngress: []
      Tags:
        - Key: Name
          Value: alimentapp-rds-sg

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subredes privadas para RDS
      SubnetIds:
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetB
      DBSubnetGroupName: !Sub alimentapp-dbsubnet-${AWS::StackName}

  PostgresDB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      EngineVersion: !Ref EngineVersion
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      DBName: !Ref DBName
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      BackupRetentionPeriod: !Ref BackupRetentionDays
      DeletionProtection: !Ref DeletionProtection
      MultiAZ: false
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref RdsSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      StorageType: gp2
      StorageEncrypted: true
      AutoMinorVersionUpgrade: true
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot

Outputs:
  VpcId:
    Value: !Ref Vpc
  PrivateSubnetIds:
    Value: !Join [',', [!Ref PrivateSubnetA, !Ref PrivateSubnetB]]
  RdsSecurityGroupId:
    Value: !Ref RdsSecurityGroup
  DbEndpointAddress:
    Value: !GetAtt PostgresDB.Endpoint.Address
  DbPort:
    Value: !GetAtt PostgresDB.Endpoint.Port
  DbIdentifier:
    Value: !Ref PostgresDB

